//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_DICT
    {
        public byte SERIAL_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string INPUT_CODE { get; set; }
        public string ITEM_CLASS { get; set; }
        public Nullable<byte> ITEM_CLASS_SORT { get; set; }
        public string PRINT_MASTER_STATION { get; set; }
        public string PAT_CLASS_STATION { get; set; }
        public string ITEM_TYPE { get; set; }
    }
}
