//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT_DICT> DEPT_DICT { get; set; }
        public virtual DbSet<PAT_CLASS_NOTE> PAT_CLASS_NOTE { get; set; }
        public virtual DbSet<PHYSICAL_MASTER_INDEX> PHYSICAL_MASTER_INDEX { get; set; }
        public virtual DbSet<T_ITEM_PREPOSITION> T_ITEM_PREPOSITION { get; set; }
        public virtual DbSet<T_LOGS> T_LOGS { get; set; }
        public virtual DbSet<T_QUEUE_HIST> T_QUEUE_HIST { get; set; }
        public virtual DbSet<T_QUEUE_LIST> T_QUEUE_LIST { get; set; }
        public virtual DbSet<T_SETS> T_SETS { get; set; }
        public virtual DbSet<T_USER> T_USER { get; set; }
        public virtual DbSet<T_DEPART_MANAGE> T_DEPART_MANAGE { get; set; }
        public virtual DbSet<T_CLINIC> T_CLINIC { get; set; }
    
        public virtual int ADDQUEUE(string pATIENTID, ObjectParameter dEPTCODE, ObjectParameter dEPTNAME, ObjectParameter dEPTNUM)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADDQUEUE", pATIENTIDParameter, dEPTCODE, dEPTNAME, dEPTNUM);
        }
    
        public virtual int ADD_CREATETIME_QUENUM(string pATIENTID, string dEPTCODE, Nullable<decimal> nUM_DEPT)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            var dEPTCODEParameter = dEPTCODE != null ?
                new ObjectParameter("DEPTCODE", dEPTCODE) :
                new ObjectParameter("DEPTCODE", typeof(string));
    
            var nUM_DEPTParameter = nUM_DEPT.HasValue ?
                new ObjectParameter("NUM_DEPT", nUM_DEPT) :
                new ObjectParameter("NUM_DEPT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_CREATETIME_QUENUM", pATIENTIDParameter, dEPTCODEParameter, nUM_DEPTParameter);
        }
    
        public virtual int COMPUTE_TWAIT(string pATIENTID, ObjectParameter rES_DEPTCODE, ObjectParameter rES_DEPTNUM)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COMPUTE_TWAIT", pATIENTIDParameter, rES_DEPTCODE, rES_DEPTNUM);
        }
    
        public virtual int FIND_MIN_DEPT(string pATIENTID, ObjectParameter dEPTCODE, ObjectParameter nUMDEPT)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FIND_MIN_DEPT", pATIENTIDParameter, dEPTCODE, nUMDEPT);
        }
    }
}
