//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEPT_DICT> DEPT_DICT { get; set; }
        public virtual DbSet<ITEM_DICT> ITEM_DICT { get; set; }
        public virtual DbSet<PAT_CLASS_NOTE> PAT_CLASS_NOTE { get; set; }
        public virtual DbSet<PHYSICAL_MASTER_INDEX> PHYSICAL_MASTER_INDEX { get; set; }
        public virtual DbSet<T_CLINIC> T_CLINIC { get; set; }
        public virtual DbSet<T_ITEM_PREPOSITION> T_ITEM_PREPOSITION { get; set; }
        public virtual DbSet<T_LOGS> T_LOGS { get; set; }
        public virtual DbSet<T_QUEUE_HIST> T_QUEUE_HIST { get; set; }
        public virtual DbSet<T_QUEUE_LIST> T_QUEUE_LIST { get; set; }
        public virtual DbSet<T_SETS> T_SETS { get; set; }
        public virtual DbSet<T_USER> T_USER { get; set; }
        public virtual DbSet<T_VOICE> T_VOICE { get; set; }
        public virtual DbSet<T_DEPART_MANAGE> T_DEPART_MANAGE { get; set; }
        public virtual DbSet<View_Screen> View_Screen { get; set; }
        public virtual DbSet<View_Screen_depart> View_Screen_depart { get; set; }
    
        public virtual int ADDQUEUE(string pATIENTID)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADDQUEUE", pATIENTIDParameter);
        }
    
        public virtual int COMPUTE_TWAIT(string pATIENTID, ObjectParameter rES_DEPTCODE, ObjectParameter rES_DEPTNAME, ObjectParameter rES_DEPTNUM)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COMPUTE_TWAIT", pATIENTIDParameter, rES_DEPTCODE, rES_DEPTNAME, rES_DEPTNUM);
        }
    
        public virtual int OVER_NUMBER(string pATIENTID, string dEPTCODE)
        {
            var pATIENTIDParameter = pATIENTID != null ?
                new ObjectParameter("PATIENTID", pATIENTID) :
                new ObjectParameter("PATIENTID", typeof(string));
    
            var dEPTCODEParameter = dEPTCODE != null ?
                new ObjectParameter("DEPTCODE", dEPTCODE) :
                new ObjectParameter("DEPTCODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OVER_NUMBER", pATIENTIDParameter, dEPTCODEParameter);
        }
    }
}
