//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAT_CLASS_NOTE
    {
        public long SERIAL_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public Nullable<byte> AMOUNT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string SEX_CODE { get; set; }
        public string CLASS_CODE { get; set; }
        public Nullable<int> ITEM_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_DETAIL_CODE { get; set; }
        public Nullable<int> NOTE_ID { get; set; }
        public string BAR_CODE { get; set; }
    }
}
