//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHYSICAL_MASTER_INDEX
    {
        public int SERIAL_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public byte AMOUNT { get; set; }
        public string PAT_VISIT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> IC_CREATE_DATE { get; set; }
        public string DEPT_CODE { get; set; }
        public string BRANCH_CODE { get; set; }
        public string ID_CARD { get; set; }
        public Nullable<short> BED_NO { get; set; }
        public string NAME { get; set; }
        public string NAME_PHONETIC { get; set; }
        public Nullable<byte> AGE { get; set; }
        public string SEX_CODE { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string COMMU_ADDR { get; set; }
        public string ADDRESS { get; set; }
        public string POST { get; set; }
        public string FAMILY_PHONE { get; set; }
        public string MOBILE_PHONE { get; set; }
        public string DUTY_CODE { get; set; }
        public string TITLE_CODE { get; set; }
        public string DUTY_CLASS { get; set; }
        public string DOCTOR { get; set; }
        public string USER_LOGID { get; set; }
        public Nullable<System.DateTime> STOP_DATE { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public Nullable<System.DateTime> INPUT_DATE { get; set; }
        public string GROUP_CODE { get; set; }
        public string INSTRUMENT_CODE { get; set; }
        public string NOTE { get; set; }
        public string SPECIMAN_CODE { get; set; }
        public string PHY_NAME { get; set; }
        public Nullable<decimal> TOTAL_CHARGE { get; set; }
        public Nullable<decimal> PATIENT_DISCOUNT { get; set; }
        public string PATIENT_GRADE { get; set; }
        public string IS_SUBSTITUTED { get; set; }
        public string SUBSTITUTE_INFO { get; set; }
        public string IS_SPECIFICAL { get; set; }
        public string SPECIFICAL_INFO { get; set; }
        public string IS_ADMINED { get; set; }
        public string CORP_NO { get; set; }
        public string INDIVIDUAL_NO { get; set; }
    }
}
