//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CLINIC
    {
        public decimal CLINIC_ID { get; set; }
        public string CLINIC_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public decimal FLOOR { get; set; }
        public string POSITION { get; set; }
        public string IP_ADDR { get; set; }
        public Nullable<decimal> SEX_CODE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<decimal> IS_USE { get; set; }
        public string RESERVE_ONE { get; set; }
        public string RESERVE_TWO { get; set; }
        public string RESERVE_THREE { get; set; }
    }
}
