//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DEPART_MANAGE
    {
        public decimal D_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public Nullable<decimal> BIGSCREEN_NUM { get; set; }
        public Nullable<decimal> SMALLSCREEN_NUM { get; set; }
        public Nullable<decimal> PREDICT_TIME { get; set; }
        public Nullable<System.DateTime> SYNCHRON_TIME { get; set; }
        public string RESERVE_ONE { get; set; }
        public string RESERVE_TWO { get; set; }
        public string RESERVE_THREE { get; set; }
        public Nullable<decimal> DYNAMIC_TIME { get; set; }
    }
}
