//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOGS
    {
        public decimal LOG_ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public string ACTION_TYPE { get; set; }
        public string IP_ADDR { get; set; }
        public string LOG_CONTENT { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<decimal> IS_EXPORT { get; set; }
        public string RESERVE_ONE { get; set; }
        public string RESERVE_TWO { get; set; }
        public string RESERVE_THREE { get; set; }
    }
}
