//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUEUE_HIST
    {
        public decimal SERIAL_NO { get; set; }
        public Nullable<decimal> QUE_ID { get; set; }
        public string ID_CARD { get; set; }
        public string PATIENT_ID { get; set; }
        public string DAPART_CODE { get; set; }
        public Nullable<decimal> QUE_NUM { get; set; }
        public Nullable<System.DateTime> CREAT_TIME { get; set; }
        public Nullable<System.DateTime> CALL_TIME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<System.DateTime> COMPLETE_TIME { get; set; }
        public Nullable<decimal> CLINIC_ID { get; set; }
        public Nullable<decimal> DOCTOR_ID { get; set; }
        public string RESERVE_ONE { get; set; }
        public string RESERVE_TWO { get; set; }
        public string RESERVE_THREE { get; set; }
        public string SEX_CODE { get; set; }
    }
}
