//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_VOICE
    {
        public decimal VOICE_ID { get; set; }
        public string PATIENT_ID { get; set; }
        public Nullable<decimal> CLINIC_ID { get; set; }
        public string DEPT_CODE { get; set; }
        public string VOICES { get; set; }
        public string RESERVE_ONE { get; set; }
        public string RESERVE_TWO { get; set; }
        public string RESERVE_THREE { get; set; }
    }
}
