//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Screen
    {
        public string DEPT_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string PATIENT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public decimal CLINIC_ID { get; set; }
        public string CLINIC_NAME { get; set; }
        public Nullable<System.DateTime> CREAT_TIME { get; set; }
    }
}
